version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-app
    environment:
      DATABASE_HOST: postgresql
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_NAME: kopoksu
      DATABASE_PORT: "5432"
      ADMIN_EMAIL: admin@kangpoksu.com
      ADMIN_PASSWORD: adminkangpoksu
      MASTER_EMAIL: master@kangpoksu.com
      MASTER_PASSWORD: masterkangpoksu
    ports:
      - "8080:8080"
    depends_on:
      - postgresql

  postgresql:
    image: postgres:latest
    container_name: postgresql-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgresql-data:/var/lib/postgresql/data
      - ./database:/docker-entrypoint-initdb.d
